name: genml_val
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - libffi=3.2.1
  - biopython=1.78
  - ca-certificates=2020.6.20
  - cerberus=1.3.2
  - certifi=2020.6.20
  - joblib=0.16.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.1
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - llvm-openmp=10.0.1
  - ncurses=6.2
  - numpy=1.19.1
  - openssl=1.1.1h
  - pandas=1.1.2
  - pip=20.2.3
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tqdm=4.49.0
  - wheel=0.35.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - newick==1.0.0

